# Azure SQL Database Data Copy Configuration
# Copy this file to config.copy.yaml and update with your settings

# Source database connection
source_db:
  server: "source-server.database.windows.net"
  database: "source-database"
  authentication_type: "sql"   # "sql" or "azure_ad"
  username: "source-username"   # required if authentication_type == sql
  password: "source-password"
  driver: "ODBC Driver 17 for SQL Server"

# Target database connection
target_db:
  server: "target-server.database.windows.net"
  database: "target-database"
  authentication_type: "sql"   # "sql" or "azure_ad"
  username: "target-username"   # required if authentication_type == sql
  password: "target-password"
  driver: "ODBC Driver 17 for SQL Server"

# Copy settings
copy:
  schema: "dbo"              # default schema for tables without schema prefix
  tables: []                  # optional list of tables (e.g., ["dbo.Customers", "Orders"]) 
  tables_file: null           # optional path to text file with tables (one per line)
  truncate: false             # truncate target before insert
  batch_size: 1000            # batch size for fetching/inserting
  identity_insert: "auto"    # auto|on|off
  retries: 3                  # transient error retries
  retry_sleep_seconds: 2.0    # sleep between retries


