# See project root for full comments; this is served for web UI convenience
source_db:
  server: "source-server.database.windows.net"
  database: "source-database"
  authentication_type: "sql"
  username: "source-username"
  password: "source-password"
  driver: "ODBC Driver 17 for SQL Server"

target_db:
  server: "target-server.database.windows.net"
  database: "target-database"
  authentication_type: "sql"
  username: "target-username"
  password: "target-password"
  driver: "ODBC Driver 17 for SQL Server"

copy:
  schema: "dbo"
  tables: []
  tables_file: null
  truncate: false
  batch_size: 1000
  identity_insert: "auto"
  retries: 3
  retry_sleep_seconds: 2.0


